# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ..til import orchestrator_msg_pb2 as til_dot_orchestrator__msg__pb2


class SchedulerCommunicatorStub(object):
    """-----------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Schedule = channel.unary_unary(
                '/til.SchedulerCommunicator/Schedule',
                request_serializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
                )
        self.GetScheduledConfigs = channel.unary_unary(
                '/til.SchedulerCommunicator/GetScheduledConfigs',
                request_serializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
                )
        self.IsScheduled = channel.unary_unary(
                '/til.SchedulerCommunicator/IsScheduled',
                request_serializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
                )
        self.RestartSchedulerLoop = channel.unary_unary(
                '/til.SchedulerCommunicator/RestartSchedulerLoop',
                request_serializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
                )
        self.SetScheduleStatus = channel.unary_unary(
                '/til.SchedulerCommunicator/SetScheduleStatus',
                request_serializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
                )
        self.GetScheduleStatus = channel.unary_unary(
                '/til.SchedulerCommunicator/GetScheduleStatus',
                request_serializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
                )
        self.DeleteScheduledConfig = channel.unary_unary(
                '/til.SchedulerCommunicator/DeleteScheduledConfig',
                request_serializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
                )
        self.Cleanup = channel.unary_unary(
                '/til.SchedulerCommunicator/Cleanup',
                request_serializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
                )


class SchedulerCommunicatorServicer(object):
    """-----------

    """

    def Schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduledConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsScheduled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartSchedulerLoop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetScheduleStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScheduledConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Schedule,
                    request_deserializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.SerializeToString,
            ),
            'GetScheduledConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduledConfigs,
                    request_deserializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.SerializeToString,
            ),
            'IsScheduled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsScheduled,
                    request_deserializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.SerializeToString,
            ),
            'RestartSchedulerLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartSchedulerLoop,
                    request_deserializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.SerializeToString,
            ),
            'SetScheduleStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetScheduleStatus,
                    request_deserializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.SerializeToString,
            ),
            'GetScheduleStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleStatus,
                    request_deserializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.SerializeToString,
            ),
            'DeleteScheduledConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScheduledConfig,
                    request_deserializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.SerializeToString,
            ),
            'Cleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.Cleanup,
                    request_deserializer=til_dot_orchestrator__msg__pb2.ScheduleRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.ScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'til.SchedulerCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchedulerCommunicator(object):
    """-----------

    """

    @staticmethod
    def Schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SchedulerCommunicator/Schedule',
            til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScheduledConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SchedulerCommunicator/GetScheduledConfigs',
            til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsScheduled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SchedulerCommunicator/IsScheduled',
            til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestartSchedulerLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SchedulerCommunicator/RestartSchedulerLoop',
            til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetScheduleStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SchedulerCommunicator/SetScheduleStatus',
            til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScheduleStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SchedulerCommunicator/GetScheduleStatus',
            til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteScheduledConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SchedulerCommunicator/DeleteScheduledConfig',
            til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SchedulerCommunicator/Cleanup',
            til_dot_orchestrator__msg__pb2.ScheduleRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class NOSUpdaterCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUpdateConfigs = channel.unary_unary(
                '/til.NOSUpdaterCommunicator/GetUpdateConfigs',
                request_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
                )
        self.GetUpdateStatus = channel.unary_unary(
                '/til.NOSUpdaterCommunicator/GetUpdateStatus',
                request_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
                )
        self.SetUpdateStatus = channel.unary_unary(
                '/til.NOSUpdaterCommunicator/SetUpdateStatus',
                request_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/til.NOSUpdaterCommunicator/Update',
                request_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
                )
        self.Cleanup = channel.unary_unary(
                '/til.NOSUpdaterCommunicator/Cleanup',
                request_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
                )


class NOSUpdaterCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUpdateConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cleanup(self, request, context):
        """rpc Delete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NOSUpdaterCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUpdateConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdateConfigs,
                    request_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.SerializeToString,
            ),
            'GetUpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdateStatus,
                    request_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.SerializeToString,
            ),
            'SetUpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUpdateStatus,
                    request_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.SerializeToString,
            ),
            'Cleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.Cleanup,
                    request_deserializer=til_dot_orchestrator__msg__pb2.NOSUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.NOSUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'til.NOSUpdaterCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NOSUpdaterCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUpdateConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.NOSUpdaterCommunicator/GetUpdateConfigs',
            til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.NOSUpdaterCommunicator/GetUpdateStatus',
            til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetUpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.NOSUpdaterCommunicator/SetUpdateStatus',
            til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.NOSUpdaterCommunicator/Update',
            til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.NOSUpdaterCommunicator/Cleanup',
            til_dot_orchestrator__msg__pb2.NOSUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.NOSUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class INUpdaterCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUpdateConfigs = channel.unary_unary(
                '/til.INUpdaterCommunicator/GetUpdateConfigs',
                request_serializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
                )
        self.GetUpdateStatus = channel.unary_unary(
                '/til.INUpdaterCommunicator/GetUpdateStatus',
                request_serializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
                )
        self.SetUpdateStatus = channel.unary_unary(
                '/til.INUpdaterCommunicator/SetUpdateStatus',
                request_serializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
                )
        self.SetDevInitModeForAccelerator = channel.unary_unary(
                '/til.INUpdaterCommunicator/SetDevInitModeForAccelerator',
                request_serializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
                )
        self.GetDevInitModeForAccelerator = channel.unary_unary(
                '/til.INUpdaterCommunicator/GetDevInitModeForAccelerator',
                request_serializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/til.INUpdaterCommunicator/Update',
                request_serializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
                )
        self.Cleanup = channel.unary_unary(
                '/til.INUpdaterCommunicator/Cleanup',
                request_serializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
                )


class INUpdaterCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUpdateConfigs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDevInitModeForAccelerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevInitModeForAccelerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cleanup(self, request, context):
        """rpc Delete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_INUpdaterCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUpdateConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdateConfigs,
                    request_deserializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.SerializeToString,
            ),
            'GetUpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdateStatus,
                    request_deserializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.SerializeToString,
            ),
            'SetUpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUpdateStatus,
                    request_deserializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.SerializeToString,
            ),
            'SetDevInitModeForAccelerator': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDevInitModeForAccelerator,
                    request_deserializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.SerializeToString,
            ),
            'GetDevInitModeForAccelerator': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevInitModeForAccelerator,
                    request_deserializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.SerializeToString,
            ),
            'Cleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.Cleanup,
                    request_deserializer=til_dot_orchestrator__msg__pb2.INUpdateRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.INUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'til.INUpdaterCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class INUpdaterCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUpdateConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.INUpdaterCommunicator/GetUpdateConfigs',
            til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.INUpdaterCommunicator/GetUpdateStatus',
            til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetUpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.INUpdaterCommunicator/SetUpdateStatus',
            til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDevInitModeForAccelerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.INUpdaterCommunicator/SetDevInitModeForAccelerator',
            til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDevInitModeForAccelerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.INUpdaterCommunicator/GetDevInitModeForAccelerator',
            til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.INUpdaterCommunicator/Update',
            til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.INUpdaterCommunicator/Cleanup',
            til_dot_orchestrator__msg__pb2.INUpdateRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.INUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TIFUpdateCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTIFCode = channel.unary_unary(
                '/til.TIFUpdateCommunicator/GetTIFCode',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFResponse.FromString,
                )
        self.UpdateTIFCode = channel.unary_unary(
                '/til.TIFUpdateCommunicator/UpdateTIFCode',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFResponse.FromString,
                )
        self.InitializeHardware = channel.unary_unary(
                '/til.TIFUpdateCommunicator/InitializeHardware',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFResponse.FromString,
                )


class TIFUpdateCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTIFCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTIFCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeHardware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TIFUpdateCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTIFCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTIFCode,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFResponse.SerializeToString,
            ),
            'UpdateTIFCode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTIFCode,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFResponse.SerializeToString,
            ),
            'InitializeHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeHardware,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'til.TIFUpdateCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TIFUpdateCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTIFCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFUpdateCommunicator/GetTIFCode',
            til_dot_orchestrator__msg__pb2.TIFRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTIFCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFUpdateCommunicator/UpdateTIFCode',
            til_dot_orchestrator__msg__pb2.TIFRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitializeHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFUpdateCommunicator/InitializeHardware',
            til_dot_orchestrator__msg__pb2.TIFRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TIFControlCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLAGMemberState = channel.unary_unary(
                '/til.TIFControlCommunicator/GetLAGMemberState',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.ChangeLAGMemberState = channel.unary_unary(
                '/til.TIFControlCommunicator/ChangeLAGMemberState',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.GetPortConfiguration = channel.unary_unary(
                '/til.TIFControlCommunicator/GetPortConfiguration',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.UpdatePortConfiguration = channel.unary_unary(
                '/til.TIFControlCommunicator/UpdatePortConfiguration',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.DeletePortConfiguration = channel.unary_unary(
                '/til.TIFControlCommunicator/DeletePortConfiguration',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.RestartPorts = channel.unary_unary(
                '/til.TIFControlCommunicator/RestartPorts',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.GetLAGConfiguration = channel.unary_unary(
                '/til.TIFControlCommunicator/GetLAGConfiguration',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.AddLAG = channel.unary_unary(
                '/til.TIFControlCommunicator/AddLAG',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.UpdateLAG = channel.unary_unary(
                '/til.TIFControlCommunicator/UpdateLAG',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.DeleteLAG = channel.unary_unary(
                '/til.TIFControlCommunicator/DeleteLAG',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.GetLAGMember = channel.unary_unary(
                '/til.TIFControlCommunicator/GetLAGMember',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.UpdateLAGMember = channel.unary_unary(
                '/til.TIFControlCommunicator/UpdateLAGMember',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.GetTableEntries = channel.unary_unary(
                '/til.TIFControlCommunicator/GetTableEntries',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.AddTableEntries = channel.unary_unary(
                '/til.TIFControlCommunicator/AddTableEntries',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.UpdateTableEntries = channel.unary_unary(
                '/til.TIFControlCommunicator/UpdateTableEntries',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.DeleteTableEntries = channel.unary_unary(
                '/til.TIFControlCommunicator/DeleteTableEntries',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )


class TIFControlCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLAGMemberState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeLAGMemberState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePortConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePortConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartPorts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLAGConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLAG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLAG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLAG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLAGMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLAGMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTableEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTableEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTableEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTableEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TIFControlCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLAGMemberState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLAGMemberState,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'ChangeLAGMemberState': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeLAGMemberState,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'GetPortConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortConfiguration,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'UpdatePortConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePortConfiguration,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'DeletePortConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePortConfiguration,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'RestartPorts': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartPorts,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'GetLAGConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLAGConfiguration,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'AddLAG': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLAG,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'UpdateLAG': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLAG,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'DeleteLAG': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLAG,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'GetLAGMember': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLAGMember,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'UpdateLAGMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLAGMember,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'GetTableEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTableEntries,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'AddTableEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTableEntries,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'UpdateTableEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTableEntries,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'DeleteTableEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTableEntries,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'til.TIFControlCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TIFControlCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLAGMemberState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/GetLAGMemberState',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeLAGMemberState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/ChangeLAGMemberState',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPortConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/GetPortConfiguration',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePortConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/UpdatePortConfiguration',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePortConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/DeletePortConfiguration',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestartPorts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/RestartPorts',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLAGConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/GetLAGConfiguration',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddLAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/AddLAG',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateLAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/UpdateLAG',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteLAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/DeleteLAG',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLAGMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/GetLAGMember',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateLAGMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/UpdateLAGMember',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTableEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/GetTableEntries',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTableEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/AddTableEntries',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTableEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/UpdateTableEntries',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTableEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.TIFControlCommunicator/DeleteTableEntries',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class RulesUpdaterCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRules = channel.unary_unary(
                '/til.RulesUpdaterCommunicator/CreateRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.DeleteRules = channel.unary_unary(
                '/til.RulesUpdaterCommunicator/DeleteRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.UpdateRules = channel.unary_unary(
                '/til.RulesUpdaterCommunicator/UpdateRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.GetRules = channel.unary_unary(
                '/til.RulesUpdaterCommunicator/GetRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.ListRules = channel.unary_unary(
                '/til.RulesUpdaterCommunicator/ListRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.Cleanup = channel.unary_unary(
                '/til.RulesUpdaterCommunicator/Cleanup',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )


class RulesUpdaterCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RulesUpdaterCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRules': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'DeleteRules': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'UpdateRules': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'GetRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'ListRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'Cleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.Cleanup,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'til.RulesUpdaterCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RulesUpdaterCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.RulesUpdaterCommunicator/CreateRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.RulesUpdaterCommunicator/DeleteRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.RulesUpdaterCommunicator/UpdateRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.RulesUpdaterCommunicator/GetRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.RulesUpdaterCommunicator/ListRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.RulesUpdaterCommunicator/Cleanup',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SwitchStateCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSwitchState = channel.unary_unary(
                '/til.SwitchStateCommunicator/GetSwitchState',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.GetSwitchStateForPort = channel.unary_unary(
                '/til.SwitchStateCommunicator/GetSwitchStateForPort',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.SetSwitchState = channel.unary_unary(
                '/til.SwitchStateCommunicator/SetSwitchState',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.SetTenantRules = channel.unary_unary(
                '/til.SwitchStateCommunicator/SetTenantRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.GetTenantRules = channel.unary_unary(
                '/til.SwitchStateCommunicator/GetTenantRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.SetProviderRules = channel.unary_unary(
                '/til.SwitchStateCommunicator/SetProviderRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )
        self.GetProviderRules = channel.unary_unary(
                '/til.SwitchStateCommunicator/GetProviderRules',
                request_serializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
                response_deserializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
                )


class SwitchStateCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSwitchState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSwitchStateForPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSwitchState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTenantRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProviderRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwitchStateCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSwitchState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSwitchState,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'GetSwitchStateForPort': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSwitchStateForPort,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'SetSwitchState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSwitchState,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'SetTenantRules': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTenantRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'GetTenantRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'SetProviderRules': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProviderRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
            'GetProviderRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderRules,
                    request_deserializer=til_dot_orchestrator__msg__pb2.TIFControlRequest.FromString,
                    response_serializer=til_dot_orchestrator__msg__pb2.TIFControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'til.SwitchStateCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SwitchStateCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSwitchState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SwitchStateCommunicator/GetSwitchState',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSwitchStateForPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SwitchStateCommunicator/GetSwitchStateForPort',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSwitchState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SwitchStateCommunicator/SetSwitchState',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTenantRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SwitchStateCommunicator/SetTenantRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTenantRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SwitchStateCommunicator/GetTenantRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProviderRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SwitchStateCommunicator/SetProviderRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProviderRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/til.SwitchStateCommunicator/GetProviderRules',
            til_dot_orchestrator__msg__pb2.TIFControlRequest.SerializeToString,
            til_dot_orchestrator__msg__pb2.TIFControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
