# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: til/tif_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15til/tif_control.proto\x12\x03til\"`\n\x06\x44pPort\x12\x0e\n\x06portId\x18\x01 \x01(\r\x12\x0e\n\x06slotId\x18\x02 \x01(\r\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12\r\n\x05speed\x18\x04 \x01(\t\x12\x0b\n\x03\x66\x65\x63\x18\x05 \x01(\t\x12\n\n\x02\x61n\x18\x06 \x01(\r\"D\n\x03Lag\x12\n\n\x02id\x18\x01 \x01(\r\x12\x12\n\nmemberbase\x18\x02 \x01(\r\x12\x1d\n\x08\x64p_ports\x18\x03 \x03(\x0b\x32\x0b.til.DpPort\";\n\x19RoutingTableConfiguration\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\tnextHopId\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'til.tif_control_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DPPORT']._serialized_start=30
  _globals['_DPPORT']._serialized_end=126
  _globals['_LAG']._serialized_start=128
  _globals['_LAG']._serialized_end=196
  _globals['_ROUTINGTABLECONFIGURATION']._serialized_start=198
  _globals['_ROUTINGTABLECONFIGURATION']._serialized_end=257
# @@protoc_insertion_point(module_scope)
